---
title: "Data Wrangling"
output: pdf_document
---


```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(here)
library(scales)

getwd()
```

```{r load data}
#read in all data
Ellerbe_wq <- read.csv(here('Data/Raw/Ellerbe_water_quality_data.csv'), 
                    stringsAsFactors = TRUE)
Sandy_wq<- read.csv(here('Data/Raw/Sandy_water_quality_data.csv'), 
                    stringsAsFactors = TRUE)
```

```{r}
#Data Wrangling
Ellerbe_wq$Dissolved_oxygen_mg.L <-
  as.numeric(as.character(Ellerbe_wq$Dissolved_oxygen_mg.L))

Sandy_wq$Dissolved_oxygen_mg.L <-
  as.numeric(as.character(Sandy_wq$Dissolved_oxygen_mg.L))

Ellerbe_wq$Sample_date<-as.Date(Ellerbe_wq$Sample_date,format="%m/%d/%Y")
Sandy_wq$Sample_date<-as.Date(Sandy_wq$Sample_date,format="%m/%d/%Y")

#add a year column
Ellerbe_wq$year <- format(Ellerbe_wq$Sample_date, "%Y")
Sandy_wq$year <- format(Sandy_wq$Sample_date, "%Y")
```

```{r}
#Plot Dissolved Oxygen in Ellerbe over the years
ggplot(Ellerbe_wq, aes(x=Sample_date,
                       y=Dissolved_oxygen_mg.L, color=year))+
  geom_point()+
   labs(x = "Sample Date",
y = "Dissolved Oxygen mg/L")+
   scale_y_continuous(breaks = c(2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0))+
   scale_x_date( breaks = date_breaks("1 year"),
                 labels = date_format("%Y"))+ 
  theme_bw()
```

